dist: trusty
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.13.1
  - 2.12.10

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls; fi'

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "XknDw37QxCTz+7vetahDDSeUI+x9KoVAkEauoS9ThnvCMX0Qoaq7OVDM5E3bZ2p0Mdo455cksGPHZXoIfoO2ZZ2+a8eDhcRgNGY2xzPaf/rLSpRMttA98czkXZCFuIG852qCUMFCsjk7O9+IiWjM/pnQE2sxAYsUPkDTtbz+2ifWrwQpY3VhyU27s+dKFSe7aGf0+ClkjU6bAOiKU9e0+1UD+YGoK4+tptkhFgcr+FcnnfMh1pCOtZ/hO99BNcjSS1Y0QqDz4Gmdi7IcjLvfxJpmG/AAa5UPhuGYr8+80rqSfyBhZqobTgMnarqZv2ih82xwnfT7S4Zb+74vqMpl5m0kEITfBLNLqk6i9FD7hqZDnWUaOVq5B5GyHII2oFWU+poazg9u8z4kIpTJZYgGomRVZ2ubZ/H+RvpxIm4TZgsWxyPnKQBeFvYY7xUPIqK12Ys17dbcdS0+Vjbe7J+S9cDzhuEWywXLbLYit2JxAZ0yJHGSYfyI5Y0454IzoZQ+tIuMTg+P31IRSBHqoUoxkYnsQyKQ/my33VuhiN9ujSc1y/z4QzUp0vf+drPlwEGm3CcpjNxq21VnlgJv6RAJUCRqr9BtzqfF+sUezt1ku4B9SpumgJQ9T/1l0YewzkrmVWvd+gUfp2reLV/+Ag/9S8mtf5WISXu22amsjXeZggo="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
